[build]
builder = "nixpacks"
buildCommand = "npm install && cd client && npm install && npm run build"

[[services]]
name = "server"
startCommand = "node server.js"

[[services]]
name = "crawler"
startCommand = "node crawler.js"